name: Deploy static content to Pages

on:
  push:
    branches: ["main"] # Roda sempre que você enviar algo para a main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Envia todos os arquivos da pasta atual (index.html, style.css, etc)
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4